### ISSUE TITLE
hammers dont give me XP

### ISSUE THREAD

**Issue by ChiloteEdgy** [nanite/JustHammers#54]
### Minecraft Version

1.18.2

### Modloader

forge 1.18.2 - 40.3.3

### Mod version

justhammers-forge-0.1.2+mc1.18.2.jar

### Latest version?

- [x] Yes

### Repeatable?

- [x] Yes

### Link to log files

noting to report here 

### Description of the issue you are having

I was mining coal when I realized that it doesn't give experience, I changed to a pillory that I had and if it gives experience, I don't know if it's a bug or something specific to the mod

### Information

- [x] I have provided as much information as possible

**Comment by ChiloteEdgy** [comment]
I also add that when I mined dirt blocks the material was not returned to me, it just disappeared.

**Comment by MichaelHillcox** [comment]
Are you playing on a modpack?

**Comment by ChiloteEdgy** [comment]
> Are you playing on a modpack?

What if I am using other mods apart from just hammers? Yes, but they are not part of a modpack created by someone, they are mods that I put on myself If the problem is that just hammers should take care of itself, it would be better to uninstall it

**Comment by MichaelHillcox** [comment]
Oh, interesting, maybe this is just a bug with 1.18.2, I can look into this :D

**Comment by ChiloteEdgy** [comment]
> Oh, interesting, maybe this is just a bug with 1.18.2, I can look into this :D

okay, I'll be waiting for a solution, it's the only mod I like to mine several blocks at the same time, I have to mine an entire mountain and without this mod it will be slow xd :(

**Comment by ChiloteEdgy** [comment]
![Image](https://github.com/user-attachments/assets/1f428cb4-67ee-4c7b-8d1e-a128e37b3204)
![Image](https://github.com/user-attachments/assets/5100ce28-4bfd-44b0-a0ee-ae40f6aacc7a)
![Image](https://github.com/user-attachments/assets/1c2bf236-733e-49d0-98eb-3b002dfe8ab1)

**Comment by MichaelHillcox** [comment]
Hey, Thanks for the bug report / feature request. This should now be resolved as of the latest version of the mod. Please update and let me know if you have an issues :+1:

**Comment by ChiloteEdgy** [comment]
emmm no new version for 1.18.2 only for 1.19.2 so the problem still happening
